---
  - name: "update apt packages."
    become: yes
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: yes
    apt:
      upgrade: yes

  - name: "download node.js"
    become: true
    shell: |
      curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -

  - name: "install nodejs"
    become: yes
    apt:
      name: ["nodejs"]
      state: latest
      update_cache: yes

  - name: "install n"
    become: yes
    npm:
      name: n
      global: yes

  - name: "install nodejs 13.8.0"
    become: yes
    shell: n 13.8.0

  - name: "install pm2"
    become: yes
    npm:
      name: pm2
      global: yes


