    npm i


- name: "Executing Node app with PM2"
  shell: |
    cd /home/ubuntu/backend/dist
    export TYPEORM_CONNECTION="postgres"
    export TYPEORM_MIGRATIONS_DIR="./migrations"
    export TYPEORM_MIGRATIONS="./migrations/*.js"
    export TYPEORM_ENTITIES="./modules/domain/**/*.entity.js"
    export TYPEORM_HOST="postgres.chllrzzzqp8g.us-east-1.rds.amazonaws.com"
    export TYPEORM_PORT="5432"
    export TYPEORM_USERNAME="postgres"
    export TYPEORM_PASSWORD="password"
    export TYPEORM_DATABASE="postgres"
    pm2 stop default
    pm2 start main.js



